version: '3.8'

services:
  web:
    build: ./app
    container_name: flask_web
    ports:
      - "8080:5000"
    volumes:
      - ./app:/app
    depends_on:
      - video_processor

  video_processor:
    image: jrottenberg/ffmpeg:latest
    container_name: video_processor
    command: >
      -re -i rtsp://root:root@192.168.146.4:554/live.sdp
      -analyzeduration 5000000
      -probesize 5000000
      -vcodec copy -f flv rtmp://rtmp_server:1935/live/stream
    depends_on:
      - rtmp_server

  rtmp_server:
    image: alfg/nginx-rtmp
    container_name: rtmp_server
    ports:
      - "1935:1935"
